### ISSUE TITLE
On tap changes color to blue

### ISSUE THREAD

**Issue by andres-moreno** [andres-moreno/twitchtv-demo#2]
Need to add CSS code to make sure that the anchor does not get selected on tap.

**Comment by andres-moreno** [comment]
The trick here was to define a:active AFTER the CSS code for a:hover.... ah, how tricky pseudo-classes can be!

**Comment by andres-moreno** [comment]
Using `media` queries one can restrict the hover behavior to devices that fully support :hover. Thus:

```css

@media (hover: none) {
    a {
        color:#f9f9fc;
    }
```
